const int oi = 2
bool a = 1

prot soma(&int[], int)
prot fatorial (&int, int) 

def init
int tchau, hey
char c = 'a'
int teste[2][2] = {1, 2, 3, 4}

int n, fat 
getint n 
do fatorial(fat, n) 
putint fat 

//do soma(tchau, hey)

while(yeah)
    putstr "hello world"
    putstr "help"

    var hola from 1 to 10 by me
    endv
endw

var hola from 1 to 10
    while(yeah)
        //algo = 2 + 2
    endw
endv

endp