const int r = 7, s = 8 

int teste[r]

prot procedimento(int, int)
//prot oi(int, int)

//int n[2] = {1, 2}

def init
    bool b0 //ele n ta apagando
    int b, c, a = 1

    c = r * a
    b = c + a + r

    //real f = 2.2
    //int a = 2, b
    //char c = 'i', d
    //putint a
    //do procedimento(1, b) //fazer ainda a semantica de passar um parametro aqui mas a variavel n ter sido declarada
    //int b

    while(!(b > c)) //erro aqui
    endw

    if(b)
    elif(c)
    endi
endp

def procedimento(int a, int b)
endp

//def oi(int a, int c)
//endp