int oi = 2

prot soma(&int[], int)

def init
int tchau, hey
char c = 'a'
do soma(tchau, hey)
while(yeah)
putstr "hello world"
putstr "help"
endw

if(ola)
getint a
getreal b
getchar c
getstr d
getout

elif(bye)
putint a
putreal b
putchar c
putstr d

else
putint 2
putreal 2.2
putchar 's'
putstr "oi"
endi

var hola from 1 dt 2 by me
if(ola)
getint a
getreal b
endi
endv
endp

def soma(int n, int m)
char result
endp