const int oi = 2
bool a = 1

prot soma(&int[], int)
prot fatorial (&int, int) 

def init
    int tchau[1], hey 
    //char c = 'a'
    do soma(tchau[], hey) //ERRO SINTATICO > sinal invalido encontrado em fator na linha 10
    while(yeah)
        putstr "hello world"
        putstr "help"
    endw

    if(ola)
        getint a
        getreal b
        getchar c
        getstr d
        getout

    elif(bye)
        putint a
        putreal b
        putchar c
        putstr d

    else
        putint 2
        putreal 2.2
        putchar 's'
        putstr "oi"
    endi

    var hola from 1 dt 2 by me
        if(ola)
            getint a
            getreal b
        endi
    endv
endp

def soma(int n, int m)
    char result
endp